name: Generate Snake Animation

on:
  schedule:
    # Runs at 5:00 UTC every day
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository so we can access the profile readme
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: abhi-1408-shek
          # Optionally, you can specify a different SVG output path
          outputs: dist/snake.svg

      # Upload the generated snake.svg to the repository
      - name: Push Generated Snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: true
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
          file: dist/snake.svg
